### PR TITLE
Add link to Replicate demo

### PR DESCRIPTION
**Pull request by fofr**
We've added LTX to Replicate here:
https://replicate.com/fofr/ltx-video

I'd love to move this to your organization on Replicate as well, so the URL would be:

https://replicate.com/lightricks/ltx-video

Please let me know if you're ok with that.

### CODE REVIEW

**Comment by yoavhacohen** [comment]
Thanks for the PR!
Can you please explain how to move this under the Lightricks organization?

**Comment by fofr** [comment]
@yoavhacohen I can do this for you, I just need the 👍

**Comment by yoavhacohen** [comment]
That would be great. Please do. Thanks!

**Comment by fofr** [comment]
I've moved the model over and updated the PR
https://replicate.com/lightricks/ltx-video

**Pull request merged**
